### ISSUE TITLE
Conflict with Repurposed Structures json loading

### ISSUE THREAD

**Issue by TelepathicGrunt** [afwitty/Skyspace-Project-1.18-Synthesis-of-Kyros#1]
Hello, I saw you had borrowed some code form RS which is fine. Just that it looks like since you kept the "repurposed structures" name in many error logging and are using RS's data folder path to read, this may cause issue with RS datapacks as both of our mods will read the json files multiple times and if your mod breaks, it'll say it is repurposed structures's fault even when my mod isnt on. 

First change to do would be to change "rs_pieces_spawn_counts" to "spsok_pieces_spawn_counts" so it now looks for json files under spsok_pieces_spawn_counts folder instead of rs_pieces_spawn_counts folder. That will stop RS datapacks form having their files read multiple times.
https://github.com/afwitty/Skyspace-Project-1.18-Synthesis-of-Kyros/blob/9149e9bffcf78950a1875d4f292c23a05f427c38/src/main/java/com/cryotron/skyspaceproject/misc/StructurePieceCountsManager.java#L29

Second changes you should do are to change all mentions of "Repurposed Structures" in these error logging to your mod's name and rs_pieces_spawn_counts to be spsok_pieces_spawn_counts so debugging issues down the road in modpacks becomes much easier.
https://github.com/afwitty/Skyspace-Project-1.18-Synthesis-of-Kyros/blob/9149e9bffcf78950a1875d4f292c23a05f427c38/src/main/java/com/cryotron/skyspaceproject/misc/StructurePieceCountsManager.java#L61

other than those two issues, it looks good to me

**Comment by afwitty** [comment]
I just read this, will take a look to see what will be changed.

Thanks Tele! :D

**Comment by afwitty** [comment]
Three commits have been made to (hopefully) resolve this issue in an ascending chronological order:

https://github.com/afwitty/Skyspace-Project-1.18-Synthesis-of-Kyros/commit/839b26737982523f7d1de5dd3ec9c3c622d5fc84
https://github.com/afwitty/Skyspace-Project-1.18-Synthesis-of-Kyros/commit/857454617116d47405b0711142d28199e1ddb6b4
https://github.com/afwitty/Skyspace-Project-1.18-Synthesis-of-Kyros/commit/6e4040d132c3fb9b812191a852c002d782731cf9
